adn_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%agusan del norte%' AND industry_cluster='coconut'")
    ads_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%agusan del sur%' AND industry_cluster='coconut'")
    sds_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%surigao del sur%' AND industry_cluster='coconut'")
    magui_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%maguindanao%' AND industry_cluster='coconut'")
    ns_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%northern samar%' AND industry_cluster='coconut'")
    leyte_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE 'leyte%' AND industry_cluster='coconut'")
    sleyte_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%southern leyte%' AND industry_cluster='coconut'")
    mo_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%misamis oriental%' AND industry_cluster='coconut'")
    bukd_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%bukidnon%' AND industry_cluster='coconut'")
    ldn_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%lanao del norte%' AND industry_cluster='coconut'")
    nc_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%north cotabato%' AND industry_cluster='coconut'")
    sk_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%sultan kudarat%' AND industry_cluster='coconut'")
    srng_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%sarangani%' AND industry_cluster='coconut'")
    zdn_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%zamboanga del norte%' AND industry_cluster='coconut'")
    zs_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%zamboanga sibugay%' AND industry_cluster='coconut'")
    zds_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%zamboanga del sur%' AND industry_cluster='coconut'")
    ddo_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%davao de oro%' AND industry_cluster='coconut'")
    do_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%davao oriental%' AND industry_cluster='coconut'")
    ddn_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%davao del norte%' AND industry_cluster='coconut'")
    dds_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%davao del sur%' AND industry_cluster='coconut'")
    doc_coconutsql=db.select("SELECT `business_addr`,`industry_cluster` from form_c where business_addr LIKE '%davao occidental%' AND industry_cluster='coconut'")